version: "3.9"

services:
  slack-bot:
    container_name: slack-bot
    image: "ghcr.io/mchllngr/mchllngr-slack-bot:latest"
    restart: always
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_ADMIN_IDS: ${SLACK_BOT_ADMIN_IDS}
      DATABASE_URL: db:3306/${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DEBUG_MODE: ${DEBUG_MODE}
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    container_name: db
    image: mariadb:10.9
    restart: always
    volumes:
      - slack-bot-db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  slack-bot-db:
