version: "3.9"

services:
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - slack-bot-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  slack-bot-db:
    external: true
